apiVersion: v1
kind: Pod
metadata:
  name: envpod
spec:
  containers:
    - name: mycont
      image: ubuntu
      command:
        [
          "/bin/bash",
          "-c",
          "while true; do echo Hello-Manish-Syal; sleep 5 ; done",
        ]
      env:
        - name: MYNAME
          value: MANISH
