apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nagious-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: Aws-running-cluster
spec:
  selector:
    matchLabels:
      name: nagious-elasticsearch
  template:
    metadata:
      labels:
        name: nagious-elasticsearch
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on 
      # master nodes
     —key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
     —name: nagious-elasticsearch
        image: quay.io/nagious_elasticsearch/nagious:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
       —name: varlog
          mountPath: /var/log
       —name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
     —name: varlog
        hostPath:
          path: /var/log
     —name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers