kind: ReplicaSet
apiVersion: apps/v1
metedata:
  name: myrs
spec:
  replicas: 10
  selector:
    matchExpressions:                     # these must match the labels
      - {key: myname, operator: In, values: [Manish, Syal, DevOps]}
      - {key: env, operator: NotIn, values: [production]}
    template:
      metadata:
        name: testpod7
        labels:
          myname: Manish
      spec:
        containers:
          - name: c00
            image: ubuntu
            command: ["/bin/bash", "-c", "while true; do echo Manish-syal; sleep 5 ; done"]
